In [3]:
import pandas as pd
Dataset = pd.read_csv("insurance_pre.csv")
Dataset = pd.get_dummies(Dataset, dtype = "int", drop_first = True)

In [4]:
Dataset

,age,bmi,children,charges,sex_male,smoker_yes
0,19,27.900,0,16884.92400,0,1
1,18,33.770,1,1725.55230,1,0
2,28,33.000,3,4449.46200,1,0
3,33,22.705,0,21984.47061,1,0
4,32,28.880,0,3866.85520,1,0
...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,1,0
1334,18,31.920,0,2205.98080,0,0
1335,18,36.850,0,1629.83350,0,0
1336,21,25.800,0,2007.94500,0,0


In [5]:
Dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='str')

In [6]:
Independent = Dataset [['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [8]:
Dependent = Dataset [['charges']]

In [11]:
from sklearn.model_selection import train_test_split
X_Train, X_Test,Y_Train,Y_Test = train_test_split(Independent,Dependent, test_size = 0.3, random_state = 0)


In [15]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_Train, Y_Train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False
Name,Type,Value
"coef_ coef_: array of shape (n_features, ) or (n_targets, n_features)Estimated coefficients for the linear regression problem.If multiple targets are passed during the fit (y 2D), thisis a 2D array of shape (n_targets, n_features), while if onlyone target is passed, this is a 1D array of length n_features.","ndarray[float64](1, 5)","[[ 257.8 , 321.06, 469.58, -41.75,23418.67]]"
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Defined only when `X`has feature names that are all strings... versionadded:: 1.0","ndarray[object](5,)","['age','bmi','children','sex_male','smoker_yes']"
"intercept_ intercept_: float or array of shape (n_targets,)Independent term in the linear model. Set to 0.0 if`fit_intercept = False`.","ndarray[float64](1,)",[-12057.24]
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,5
rank_ rank_: intRank of matrix `X`. Only available when `X` is dense.,int64,np.int64(5)


In [19]:
weight = regressor.coef_
weight

array([[  257.8006705 ,   321.06004271,   469.58113407,   -41.74825718,
        23418.6671912 ]])

In [20]:
bias = regressor.intercept_
bias

array([-12057.244846])

In [21]:
Y_Pred = regressor.predict(X_Test)
Y_Pred

array([[11472.23618644],
       [ 9958.50125569],
       [37657.06917237],
       [15949.13223617],
       [ 6885.72312017],
       [ 3528.88810655],
       [ 1031.86224676],
       [14181.1024054 ],
       [ 8847.14792524],
       [ 7275.30131109],
       [ 4216.86216451],
       [10190.14526672],
       [ 9097.46039634],
       [ 4255.14691858],
       [27430.50340855],
       [11282.58288365],
       [11177.22736522],
       [ 5504.64625133],
       [ 8030.81149341],
       [26327.41490839],
       [33367.35431038],
       [14177.00561427],
       [11261.11883838],
       [32413.15484705],
       [ 4414.81928993],
       [ 8606.98618122],
       [  712.30206629],
       [10258.50678538],
       [ 4198.66143865],
       [10231.92533963],
       [ 8874.73800132],
       [40207.90493832],
       [15892.29406482],
       [14055.58336707],
       [24136.79051345],
       [ 4643.98226168],
       [12953.8618379 ],
       [30694.2595505 ],
       [33135.3543329 ],
       [ 3790.06798605],


In [23]:
from sklearn.metrics import r2_score
r_value = r2_score(Y_Test, Y_Pred)
r_value

0.7894790349867009

In [26]:
import pickle as pc
Filename = "MLR_Assignment_Multiple_Linear_Regression_Model.sav"
Filename

'MLR_Assignment_Multiple_Linear_Regression_Model.sav'

In [27]:
pc.dump(regressor,open(Filename, 'wb'))

In [30]:
Loaded_file = pc.load(open("MLR_Assignment_Multiple_Linear_Regression_Model.sav",'rb'))
Result = Loaded_file.predict([[43,30.970,1,0,0]])
Result

E:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[9440.99464203]])