In [4]:
#####  Phase1 : Model Creation #####
#####  Data Loading  ######
#Imports the pandas library for handling datasets /database / tables
import pandas as pd
ProductSet = pd.read_csv("Product_Finder_sample.csv")
ProductSet

,Multiplier,Product
0,1,4
1,2,8
2,3,12
3,4,16
4,5,20
5,6,24
6,7,28
7,8,32
8,9,36
9,10,40


In [6]:
Inp = ProductSet [["Multiplier"]]
Inp

,Multiplier
0,1
1,2
2,3
3,4
4,5
5,6
6,7
7,8
8,9
9,10


In [8]:
Out = ProductSet[["Product"]]
Out

,Product
0,4
1,8
2,12
3,16
4,20
5,24
6,28
7,32
8,36
9,40


In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train, Y_test = train_test_split(Inp, Out,test_size = 0.30, random_state = 0)

In [11]:
X_train

,Multiplier
6,7
13,14
4,5
2,3
5,6
14,15
9,10
7,8
16,17
11,12


In [12]:
X_test

,Multiplier
18,19
1,2
19,20
8,9
10,11
17,18


In [13]:
Y_train

,Product
6,28
13,56
4,20
2,12
5,24
14,60
9,40
7,32
16,68
11,48


In [14]:
Y_test

,Product
18,76
1,8
19,80
8,36
10,44
17,72


In [16]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,Y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False
Name,Type,Value
"coef_ coef_: array of shape (n_features, ) or (n_targets, n_features)Estimated coefficients for the linear regression problem.If multiple targets are passed during the fit (y 2D), thisis a 2D array of shape (n_targets, n_features), while if onlyone target is passed, this is a 1D array of length n_features.","ndarray[float64](1, 1)",[[4.]]
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Defined only when `X`has feature names that are all strings... versionadded:: 1.0","ndarray[object](1,)",['Multiplier']
"intercept_ intercept_: float or array of shape (n_targets,)Independent term in the linear model. Set to 0.0 if`fit_intercept = False`.","ndarray[float64](1,)",[0.]
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,1
rank_ rank_: intRank of matrix `X`. Only available when `X` is dense.,int64,np.int64(1)


In [17]:
weight = regressor.coef_
weight

array([[4.]])

In [18]:
bias = regressor.intercept_
bias

array([7.10542736e-15])

In [21]:
Y_predi = regressor.predict(X_test)
Y_predi

array([[76.],
       [ 8.],
       [80.],
       [36.],
       [44.],
       [72.]])

In [23]:
from sklearn.metrics import r2_score
R_Score = r2_score(Y_test,Y_predi)
R_Score

1.0

In [25]:
import pickle as pc
Filename = "SLR_Model_ProductFinder_Predict.sav"
Filename

'SLR_Model_ProductFinder_Predict.sav'

In [26]:
pc.dump(regressor, open(Filename,'wb'))


In [33]:
Loaded_Model = pc.load(open(Filename,'rb'))
Result1 = Loaded_Model.predict([[25]])
Result1

E:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[100.]])