In [87]:
#####  Phase1 : Model Creation:  #####
#####  Data Loading  ######

In [59]:
#Imports the pandas library for handling datasets /database / tables
import pandas as pd

In [60]:
#Reads the CSV file into a pandas DataFrame Variable "Dataset"  
Dataset = pd.read_csv("Salary_data.csv")

In [61]:
#to display the dataset (rows and columns).
Dataset

,YearsExperience,Salary
0,1.1,39343.0
1,1.3,46205.0
2,1.5,37731.0
3,2.0,43525.0
4,2.2,39891.0
5,2.9,56642.0
6,3.0,60150.0
7,3.2,54445.0
8,3.2,64445.0
9,3.7,57189.0


In [65]:
#####  Feature Selection  ######

In [63]:
#Set the independent variable (Years of Experience)
Independent = Dataset[["YearsExperience"]]
#To display the Independent -Input Values
Independent

,YearsExperience
0,1.1
1,1.3
2,1.5
3,2.0
4,2.2
5,2.9
6,3.0
7,3.2
8,3.2
9,3.7


In [64]:
#Set the dependent variable (Salary)
Dependent = Dataset[["Salary"]]
#To display the Dependent -Output Values
Dependent

,Salary
0,39343.0
1,46205.0
2,37731.0
3,43525.0
4,39891.0
5,56642.0
6,60150.0
7,54445.0
8,64445.0
9,57189.0


In [66]:
######  Train-Test Split ######

In [67]:
#Imports the function to split data sklearn library and function model_selection.
from sklearn.model_selection import train_test_split
#Splits data into training and testing sets (30% test, 70% train).
train_test_split(Independent, Dependent,test_size=0.30,random_state=0)

[    YearsExperience
 22              7.9
 5               2.9
 16              5.1
 8               3.2
 14              4.5
 23              8.2
 20              6.8
 1               1.3
 29             10.5
 6               3.0
 4               2.2
 18              5.9
 19              6.0
 9               3.7
 7               3.2
 25              9.0
 3               2.0
 0               1.1
 21              7.1
 15              4.9
 12              4.0,
     YearsExperience
 2               1.5
 28             10.3
 13              4.1
 10              3.9
 26              9.5
 24              8.7
 27              9.6
 11              4.0
 17              5.3,
       Salary
 22  101302.0
 5    56642.0
 16   66029.0
 8    64445.0
 14   61111.0
 23  113812.0
 20   91738.0
 1    46205.0
 29  121872.0
 6    60150.0
 4    39891.0
 18   81363.0
 19   93940.0
 9    57189.0
 7    54445.0
 25  105582.0
 3    43525.0
 0    39343.0
 21   98273.0
 15   67938.0
 12   56957.0,
       Salary
 2 

In [68]:
#Assigns training and testing sets to variables.
from sklearn.model_selection import train_test_split
X_Train,X_Test,Y_Train,Y_Test = train_test_split(Independent, Dependent,test_size=0.30,random_state=0)

In [69]:
#Training data for independent variable.
X_Train

,YearsExperience
22,7.9
5,2.9
16,5.1
8,3.2
14,4.5
23,8.2
20,6.8
1,1.3
29,10.5
6,3.0


In [70]:
#Testing data for independent variable.
X_Test

,YearsExperience
2,1.5
28,10.3
13,4.1
10,3.9
26,9.5
24,8.7
27,9.6
11,4.0
17,5.3


In [71]:
#Training data for dependent variable.
Y_Train

,Salary
22,101302.0
5,56642.0
16,66029.0
8,64445.0
14,61111.0
23,113812.0
20,91738.0
1,46205.0
29,121872.0
6,60150.0


In [72]:
#Testing data for dependent variable.
Y_Test

,Salary
2,37731.0
28,122391.0
13,57081.0
10,63218.0
26,116969.0
24,109431.0
27,112635.0
11,55794.0
17,83088.0


In [73]:
#####  Model Training  #####

In [74]:
#Imports Linear Regression model
from sklearn.linear_model import LinearRegression
#Creates a regression model object.
regressor = LinearRegression()
#Trains the model using training data(Input and output data).
regressor.fit(X_Train,Y_Train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False
Name,Type,Value
"coef_ coef_: array of shape (n_features, ) or (n_targets, n_features)Estimated coefficients for the linear regression problem.If multiple targets are passed during the fit (y 2D), thisis a 2D array of shape (n_targets, n_features), while if onlyone target is passed, this is a 1D array of length n_features.","ndarray[float64](1, 1)",[[9360.26]]
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Defined only when `X`has feature names that are all strings... versionadded:: 1.0","ndarray[object](1,)",['YearsExperience']
"intercept_ intercept_: float or array of shape (n_targets,)Independent term in the linear model. Set to 0.0 if`fit_intercept = False`.","ndarray[float64](1,)",[26777.39]
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,1
rank_ rank_: intRank of matrix `X`. Only available when `X` is dense.,int64,np.int64(1)


In [75]:
#####  Model Parameters  #####

In [76]:
#Retrieves the slope(w) (coefficient) of the regression line.
weight = regressor.coef_
weight

array([[9360.26128619]])

In [77]:
#Retrieves the intercept(b) of the regression line.
bias = regressor.intercept_
bias

array([26777.3913412])

In [78]:
#####  Prediction  #####

In [79]:
#Predicts salaries for test data.
Y_Pred = regressor.predict(X_Test)
#To display predicted salary values.
Y_Pred

array([[ 40817.78327049],
       [123188.08258899],
       [ 65154.46261459],
       [ 63282.41035735],
       [115699.87356004],
       [108211.66453108],
       [116635.89968866],
       [ 64218.43648597],
       [ 76386.77615802]])

In [80]:
#####  Model Evaluation  #####

In [81]:
#Imports R² score function
from sklearn.metrics import r2_score 
#Calculates accuracy of the model (how well predictions fit actual data).
R_Score = r2_score(Y_Test, Y_Pred)
#To display the R² score.
R_Score

0.9740993407213511

In [82]:
#####  Model Saving & Loading  #####

In [83]:
#Imports pickle for saving/loading models.
import pickle
#Defines filename for saving model.
FileName = "SLR_Model_HR_Salary_Predict.sav"

In [84]:
#Saves trained model to file.
pickle.dump(regressor,open(FileName,'wb'))

In [85]:
#Loads saved model back.
Loaded_Model = pickle.load(open( "SLR_Model_HR_Salary_Predict.sav",'rb'))
#Predicts salary for 15 years of experience using loaded model.
Result = Loaded_Model.predict([[15]])
#To display the predicted salary.
Result

E:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[167181.3106341]])

In [54]:
Loaded_Model = pickle.load(open( "SLR_Model_HR_Salary_Predict.sav",'rb'))
Result = Loaded_Model.predict([[2.0]])
Result

E:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[45497.91391358]])

In [55]:
Loaded_Model = pickle.load(open( "SLR_Model_HR_Salary_Predict.sav",'rb'))
Result = Loaded_Model.predict([[13]])
Result

E:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[148460.78806172]])