In [44]:
#####  Phase1 : Model Creation : 50_StandUps Profit Predict  #####
#####  Data Loading  ######
#Imports the pandas library for handling datasets /database / tables
import pandas as pd

In [45]:
#Reads the CSV file into a pandas DataFrame Variable "Dataset"  
Dataset = pd.read_csv("50_Startups.csv")
#to display the dataset (rows and columns).
Dataset

,R&D Spend,Administration,Marketing Spend,State,Profit
0,165349.20,136897.80,471784.10,New York,192261.83
1,162597.70,151377.59,443898.53,California,191792.06
2,153441.51,101145.55,407934.54,Florida,191050.39
3,144372.41,118671.85,383199.62,New York,182901.99
4,142107.34,91391.77,366168.42,Florida,166187.94
5,131876.90,99814.71,362861.36,New York,156991.12
6,134615.46,147198.87,127716.82,California,156122.51
7,130298.13,145530.06,323876.68,Florida,155752.60
8,120542.52,148718.95,311613.29,New York,152211.77
9,123334.88,108679.17,304981.62,California,149759.96


In [46]:
#Converts categorical columns into dummy/indicator variables (numerical form).
#Ensures the dummy values are stored as integers (0 and 1) instead of True/False.
#Drops the first category in each categorical column to avoid the dummy variable trap (multicollinearity).
Dataset = pd.get_dummies(Dataset, dtype = int, drop_first = True)
Dataset

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,0,1
1,162597.70,151377.59,443898.53,191792.06,0,0
2,153441.51,101145.55,407934.54,191050.39,1,0
3,144372.41,118671.85,383199.62,182901.99,0,1
4,142107.34,91391.77,366168.42,166187.94,1,0
5,131876.90,99814.71,362861.36,156991.12,0,1
6,134615.46,147198.87,127716.82,156122.51,0,0
7,130298.13,145530.06,323876.68,155752.60,1,0
8,120542.52,148718.95,311613.29,152211.77,0,1
9,123334.88,108679.17,304981.62,149759.96,0,0


In [47]:
#Returns the list of all column names present in the DataFrame Dataset.
Dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='str')

In [48]:
#####  Feature Selection  ######
#Set the independent variables ('R&D Spend', 'Administration', 'Marketing Spend', 'State_Florida', 'State_New York')
Independent = Dataset[['R&D Spend', 'Administration', 'Marketing Spend', 'State_Florida', 'State_New York']]
#To display the Independent -Input Values
Independent

,R&D Spend,Administration,Marketing Spend,State_Florida,State_New York
0,165349.20,136897.80,471784.10,0,1
1,162597.70,151377.59,443898.53,0,0
2,153441.51,101145.55,407934.54,1,0
3,144372.41,118671.85,383199.62,0,1
4,142107.34,91391.77,366168.42,1,0
5,131876.90,99814.71,362861.36,0,1
6,134615.46,147198.87,127716.82,0,0
7,130298.13,145530.06,323876.68,1,0
8,120542.52,148718.95,311613.29,0,1
9,123334.88,108679.17,304981.62,0,0


In [49]:
#Set the dependent variable (Profit)
Dependent = Dataset[['Profit']]
#To display the Dependent -Output Values
Dependent

,Profit
0,192261.83
1,191792.06
2,191050.39
3,182901.99
4,166187.94
5,156991.12
6,156122.51
7,155752.60
8,152211.77
9,149759.96


In [50]:
######  Train-Test Split ######
#Imports the function to split data sklearn library and function model_selection.
from sklearn.model_selection import train_test_split
#Splits data into training and testing sets (30% test, 70% train) and Assigns training and testing sets to variables.
X_Train, X_Test, Y_Train, Y_Test = train_test_split(Independent, Dependent, test_size = 0.30, random_state = 0)

In [51]:
#Training data for independent variables.
X_Train

,R&D Spend,Administration,Marketing Spend,State_Florida,State_New York
7,130298.13,145530.06,323876.68,1,0
14,119943.24,156547.42,256512.92,1,0
45,1000.23,124153.04,1903.93,0,1
48,542.05,51743.15,0.00,0,1
29,65605.48,153032.06,107138.38,0,1
15,114523.61,122616.84,261776.23,0,1
30,61994.48,115641.28,91131.24,1,0
32,63408.86,129219.61,46085.25,0,0
16,78013.11,121597.55,264346.06,0,0
42,23640.93,96189.63,148001.11,0,0


In [52]:
#Testing data for independent variables.
X_Test

,R&D Spend,Administration,Marketing Spend,State_Florida,State_New York
28,66051.52,182645.56,118148.20,1,0
11,100671.96,91790.61,249744.55,0,0
10,101913.08,110594.11,229160.95,1,0
41,27892.92,84710.77,164470.71,1,0
2,153441.51,101145.55,407934.54,1,0
27,72107.60,127864.55,353183.81,0,1
38,20229.59,65947.93,185265.10,0,1
31,61136.38,152701.92,88218.23,0,1
22,73994.56,122782.75,303319.26,1,0
4,142107.34,91391.77,366168.42,1,0


In [53]:
#Training data for dependent variable.
Y_Train

,Profit
7,155752.60
14,132602.65
45,64926.08
48,35673.41
29,101004.64
15,129917.04
30,99937.59
32,97427.84
16,126992.93
42,71498.49


In [54]:
#Testing data for dependent variable.
Y_Test

,Profit
28,103282.38
11,144259.40
10,146121.95
41,77798.83
2,191050.39
27,105008.31
38,81229.06
31,97483.56
22,110352.25
4,166187.94


In [55]:
#####  Model Training  #####
#Imports Linear Regression model
from sklearn.linear_model import LinearRegression
#Creates a regression model object.
regressor = LinearRegression()
#Trains the model using training data(Input and output data).
regressor.fit(X_Train, Y_Train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False
Name,Type,Value
"coef_ coef_: array of shape (n_features, ) or (n_targets, n_features)Estimated coefficients for the linear regression problem.If multiple targets are passed during the fit (y 2D), thisis a 2D array of shape (n_targets, n_features), while if onlyone target is passed, this is a 1D array of length n_features.","ndarray[float64](1, 5)","[[ 0.79, 0.03, 0.03,463.03,304.8 ]]"
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Defined only when `X`has feature names that are all strings... versionadded:: 1.0","ndarray[object](5,)","['R&D Spend','Administration','Marketing Spend','State_Florida', 'State_New York']"
"intercept_ intercept_: float or array of shape (n_targets,)Independent term in the linear model. Set to 0.0 if`fit_intercept = False`.","ndarray[float64](1,)",[42403.87]
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,5
rank_ rank_: intRank of matrix `X`. Only available when `X` is dense.,int64,np.int64(5)


In [56]:
#####  Model Parameters  #####
#Retrieves the slope(w) (coefficient) of the regression line.
weight = regressor.coef_
weight

array([[7.90840255e-01, 3.01968165e-02, 3.10148566e-02, 4.63028992e+02,
        3.04799573e+02]])

In [57]:
#Retrieves the intercept(b) of the regression line.
bias = regressor.intercept_
bias

array([42403.87087053])

In [58]:
#####  Prediction  #####
#Predicts salaries for test data.
Y_Predict = regressor.predict(X_Test)
#To display predicted salary values.
Y_Predict

array([[104282.76472172],
       [132536.88499212],
       [133910.85007766],
       [ 72584.77489417],
       [179920.9276189 ],
       [114549.31079234],
       [ 66444.43261346],
       [ 98404.96840122],
       [114499.82808602],
       [169367.50639895],
       [ 96522.6253998 ],
       [ 88040.6718287 ],
       [110949.99405525],
       [ 90419.1897851 ],
       [128020.46250064]])

In [59]:
#####  Model Evaluation  #####
#Imports R² score function
from sklearn.metrics import r2_score
#Calculates accuracy of the model (how well predictions fit actual data).
R_Score = r2_score(Y_Test, Y_Predict)
#To display the R² score.
R_Score

0.9358680970046243

In [60]:
#####  Model Saving & Loading  #####
#Imports pickle for saving/loading models.
import pickle as pc
#Defines filename for saving model.
FileName = "MLR_50StartUps_Phase1_Model.sav"
FileName

'MLR_50StartUps_Phase1_Model.sav'

In [61]:
#Saves trained model to file.
pc.dump(regressor,open(FileName,'wb'))

In [62]:
#Loads saved model back.
Loaded_Model = pc.load(open("MLR_50StartUps_Phase1_Model.sav",'rb'))
#Predicts profit using loaded model.
Result = Loaded_Model.predict([[22180.74, 154900.14,28400.72,1,0]])
#To display the predicted profit.
Result

E:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[65966.65730513]])